//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingService
    {
        public int BookingServiceID { get; set; }
        public int BookingDetailID { get; set; }
        public int BookingID { get; set; }
        public int RoomID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string Note { get; set; }
    
        public virtual BookingDetail BookingDetail { get; set; }
        public virtual Room Room { get; set; }
        public virtual Service Service { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
