//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingDetail()
        {
            this.BookingServices = new HashSet<BookingService>();
        }
    
        public int BookingDetailID { get; set; }
        public int BookingID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public Nullable<int> SONGAYO { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public decimal RoomPrice { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingService> BookingServices { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
