//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int RoomTypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> BedNumbers { get; set; }
        public Nullable<int> HumanCapacity { get; set; }
        public Nullable<int> StandardCapacity { get; set; }
        public Nullable<int> AdultCapacity { get; set; }
        public Nullable<int> ChildCapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
